package gintong.phoenix.knowledge.old.vo;


// Generated 2016-6-5 9:54:44 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TbCategory generated by hbm2java
 */
public class TbCategory implements java.io.Serializable {

	private Long id;
	private Long uid;
	private String name;
	private Long parentId;
	private String sortId;
	private String state;
	private Date subtime;
	private Date modtime;

	public TbCategory() {
	}

	public TbCategory(Date subtime) {
		this.subtime = subtime;
	}

	public TbCategory(Long uid, String name, Long parentId, String sortId, String state, Date subtime, Date modtime) {
		this.uid = uid;
		this.name = name;
		this.parentId = parentId;
		this.sortId = sortId;
		this.state = state;
		this.subtime = subtime;
		this.modtime = modtime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public String getSortId() {
		return this.sortId;
	}

	public void setSortId(String sortId) {
		this.sortId = sortId;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Date getSubtime() {
		return this.subtime;
	}

	public void setSubtime(Date subtime) {
		this.subtime = subtime;
	}

	public Date getModtime() {
		return this.modtime;
	}

	public void setModtime(Date modtime) {
		this.modtime = modtime;
	}

}
