package gintong.phoenix.knowledge.old.vo;


// Generated 2016-6-5 9:54:44 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TbKnowledgeCollection generated by hbm2java
 */
public class TbKnowledgeCollection implements java.io.Serializable {

	private Long id;
	private Long knowledgeId;
	private Date createtime;
	private Integer source;
	private Long categoryId;
	private String collectionTags;
	private String collectionComment;
	private Long userId;

	public TbKnowledgeCollection() {
	}

	public TbKnowledgeCollection(Long knowledgeId, Date createtime, Integer source, Long categoryId,
			String collectionTags, String collectionComment, Long userId) {
		this.knowledgeId = knowledgeId;
		this.createtime = createtime;
		this.source = source;
		this.categoryId = categoryId;
		this.collectionTags = collectionTags;
		this.collectionComment = collectionComment;
		this.userId = userId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getKnowledgeId() {
		return this.knowledgeId;
	}

	public void setKnowledgeId(Long knowledgeId) {
		this.knowledgeId = knowledgeId;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Integer getSource() {
		return this.source;
	}

	public void setSource(Integer source) {
		this.source = source;
	}

	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	public String getCollectionTags() {
		return this.collectionTags;
	}

	public void setCollectionTags(String collectionTags) {
		this.collectionTags = collectionTags;
	}

	public String getCollectionComment() {
		return this.collectionComment;
	}

	public void setCollectionComment(String collectionComment) {
		this.collectionComment = collectionComment;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

}
