package gintong.phoenix.knowledge.old.vo;


// Generated 2016-6-5 9:54:44 by Hibernate Tools 4.3.1.Final

/**
 * TbKnowledgeStatics generated by hbm2java
 */
public class TbKnowledgeStatics implements java.io.Serializable {

	private long knowledgeId;
	private Long commentCount;
	private Long shareCount;
	private Long collectionCount;
	private Long clickCount;
	private Short source;
	private Short type;

	public TbKnowledgeStatics() {
	}

	public TbKnowledgeStatics(long knowledgeId) {
		this.knowledgeId = knowledgeId;
	}

	public TbKnowledgeStatics(long knowledgeId, Long commentCount, Long shareCount, Long collectionCount,
			Long clickCount, Short source, Short type) {
		this.knowledgeId = knowledgeId;
		this.commentCount = commentCount;
		this.shareCount = shareCount;
		this.collectionCount = collectionCount;
		this.clickCount = clickCount;
		this.source = source;
		this.type = type;
	}

	public long getKnowledgeId() {
		return this.knowledgeId;
	}

	public void setKnowledgeId(long knowledgeId) {
		this.knowledgeId = knowledgeId;
	}

	public Long getCommentCount() {
		return this.commentCount;
	}

	public void setCommentCount(Long commentCount) {
		this.commentCount = commentCount;
	}

	public Long getShareCount() {
		return this.shareCount;
	}

	public void setShareCount(Long shareCount) {
		this.shareCount = shareCount;
	}

	public Long getCollectionCount() {
		return this.collectionCount;
	}

	public void setCollectionCount(Long collectionCount) {
		this.collectionCount = collectionCount;
	}

	public Long getClickCount() {
		return this.clickCount;
	}

	public void setClickCount(Long clickCount) {
		this.clickCount = clickCount;
	}

	public Short getSource() {
		return this.source;
	}

	public void setSource(Short source) {
		this.source = source;
	}

	public Short getType() {
		return this.type;
	}

	public void setType(Short type) {
		this.type = type;
	}

}
