package gintong.phoenix.knowledge.old.vo;


// Generated 2016-6-5 9:54:44 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TbKnowledgeBase generated by hbm2java
 */
public class TbKnowledgeBase implements java.io.Serializable {

	private long knowledgeId;
	private Long userId;
	private String title;
	private String author;
	private String path;
	private Date createtime;
	private String tag;
	private String CDesc;
	private Long columnId;
	private String picPath;
	private Short columnType;
	private Short essence;
	private String taskid;
	private Integer userStar;

	public TbKnowledgeBase() {
	}

	public TbKnowledgeBase(long knowledgeId) {
		this.knowledgeId = knowledgeId;
	}

	public TbKnowledgeBase(long knowledgeId, Long userId, String title, String author, String path, Date createtime,
			String tag, String CDesc, Long columnId, String picPath, Short columnType, Short essence, String taskid,
			Integer userStar) {
		this.knowledgeId = knowledgeId;
		this.userId = userId;
		this.title = title;
		this.author = author;
		this.path = path;
		this.createtime = createtime;
		this.tag = tag;
		this.CDesc = CDesc;
		this.columnId = columnId;
		this.picPath = picPath;
		this.columnType = columnType;
		this.essence = essence;
		this.taskid = taskid;
		this.userStar = userStar;
	}

	public long getKnowledgeId() {
		return this.knowledgeId;
	}

	public void setKnowledgeId(long knowledgeId) {
		this.knowledgeId = knowledgeId;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public String getCDesc() {
		return this.CDesc;
	}

	public void setCDesc(String CDesc) {
		this.CDesc = CDesc;
	}

	public Long getColumnId() {
		return this.columnId;
	}

	public void setColumnId(Long columnId) {
		this.columnId = columnId;
	}

	public String getPicPath() {
		return this.picPath;
	}

	public void setPicPath(String picPath) {
		this.picPath = picPath;
	}

	public Short getColumnType() {
		return this.columnType;
	}

	public void setColumnType(Short columnType) {
		this.columnType = columnType;
	}

	public Short getEssence() {
		return this.essence;
	}

	public void setEssence(Short essence) {
		this.essence = essence;
	}

	public String getTaskid() {
		return this.taskid;
	}

	public void setTaskid(String taskid) {
		this.taskid = taskid;
	}

	public Integer getUserStar() {
		return this.userStar;
	}

	public void setUserStar(Integer userStar) {
		this.userStar = userStar;
	}

}
