package gintong.phoenix.knowledge.old.vo;


// Generated 2016-6-5 9:54:44 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TbKnowledgeReport generated by hbm2java
 */
public class TbKnowledgeReport implements java.io.Serializable {

	private Long id;
	private Long knowledgeId;
	private String type;
	private String repDesc;
	private Date createtime;
	private Long userId;
	private String userName;
	private String knowledgeTitle;
	private Date updateTime;
	private String results;
	private Integer status;
	private Short columnType;

	public TbKnowledgeReport() {
	}

	public TbKnowledgeReport(Long knowledgeId, String type, String repDesc, Date createtime, Long userId,
			String userName, String knowledgeTitle, Date updateTime, String results, Integer status, Short columnType) {
		this.knowledgeId = knowledgeId;
		this.type = type;
		this.repDesc = repDesc;
		this.createtime = createtime;
		this.userId = userId;
		this.userName = userName;
		this.knowledgeTitle = knowledgeTitle;
		this.updateTime = updateTime;
		this.results = results;
		this.status = status;
		this.columnType = columnType;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getKnowledgeId() {
		return this.knowledgeId;
	}

	public void setKnowledgeId(Long knowledgeId) {
		this.knowledgeId = knowledgeId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getRepDesc() {
		return this.repDesc;
	}

	public void setRepDesc(String repDesc) {
		this.repDesc = repDesc;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getKnowledgeTitle() {
		return this.knowledgeTitle;
	}

	public void setKnowledgeTitle(String knowledgeTitle) {
		this.knowledgeTitle = knowledgeTitle;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getResults() {
		return this.results;
	}

	public void setResults(String results) {
		this.results = results;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Short getColumnType() {
		return this.columnType;
	}

	public void setColumnType(Short columnType) {
		this.columnType = columnType;
	}

}
