package gintong.phoenix.knowledge.old.vo;


// Generated 2016-6-5 9:54:44 by Hibernate Tools 4.3.1.Final

/**
 * TbKnowledgeCategory generated by hbm2java
 */
public class TbKnowledgeCategory implements java.io.Serializable {

	private Long id;
	private Long knowledgeId;
	private Long categoryId;
	private Character status;

	public TbKnowledgeCategory() {
	}

	public TbKnowledgeCategory(Long knowledgeId, Long categoryId, Character status) {
		this.knowledgeId = knowledgeId;
		this.categoryId = categoryId;
		this.status = status;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getKnowledgeId() {
		return this.knowledgeId;
	}

	public void setKnowledgeId(Long knowledgeId) {
		this.knowledgeId = knowledgeId;
	}

	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

}
