package gintong.phoenix.knowledge.old.vo;


// Generated 2016-6-5 9:54:44 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TbKnowledgeComment generated by hbm2java
 */
public class TbKnowledgeComment implements java.io.Serializable {

	private Long id;
	private Long knowledgeId;
	private String content;
	private Date createtime;
	private Boolean status;
	private Long parentid;
	private Long userId;
	private Long count;
	private String username;
	private String pic;
	private Byte isVisible;
	private Byte isDelete;
	private Date deleteTime;
	private Long deleteUserId;

	public TbKnowledgeComment() {
	}

	public TbKnowledgeComment(Long knowledgeId, String content, Date createtime, Boolean status, Long parentid,
			Long userId, Long count, String username, String pic, Byte isVisible, Byte isDelete, Date deleteTime,
			Long deleteUserId) {
		this.knowledgeId = knowledgeId;
		this.content = content;
		this.createtime = createtime;
		this.status = status;
		this.parentid = parentid;
		this.userId = userId;
		this.count = count;
		this.username = username;
		this.pic = pic;
		this.isVisible = isVisible;
		this.isDelete = isDelete;
		this.deleteTime = deleteTime;
		this.deleteUserId = deleteUserId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getKnowledgeId() {
		return this.knowledgeId;
	}

	public void setKnowledgeId(Long knowledgeId) {
		this.knowledgeId = knowledgeId;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Long getParentid() {
		return this.parentid;
	}

	public void setParentid(Long parentid) {
		this.parentid = parentid;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getCount() {
		return this.count;
	}

	public void setCount(Long count) {
		this.count = count;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPic() {
		return this.pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

	public Byte getIsVisible() {
		return this.isVisible;
	}

	public void setIsVisible(Byte isVisible) {
		this.isVisible = isVisible;
	}

	public Byte getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Byte isDelete) {
		this.isDelete = isDelete;
	}

	public Date getDeleteTime() {
		return this.deleteTime;
	}

	public void setDeleteTime(Date deleteTime) {
		this.deleteTime = deleteTime;
	}

	public Long getDeleteUserId() {
		return this.deleteUserId;
	}

	public void setDeleteUserId(Long deleteUserId) {
		this.deleteUserId = deleteUserId;
	}

}
