package gintong.phoenix.knowledge.old.vo;


// Generated 2016-6-5 9:54:44 by Hibernate Tools 4.3.1.Final

/**
 * TbUserTags generated by hbm2java
 */
public class TbUserTags implements java.io.Serializable {

	private Long tagId;
	private Long userId;
	private String tagname;

	public TbUserTags() {
	}

	public TbUserTags(Long userId, String tagname) {
		this.userId = userId;
		this.tagname = tagname;
	}

	public Long getTagId() {
		return this.tagId;
	}

	public void setTagId(Long tagId) {
		this.tagId = tagId;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getTagname() {
		return this.tagname;
	}

	public void setTagname(String tagname) {
		this.tagname = tagname;
	}

}
