package gintong.phoenix.knowledge.old.vo;


// Generated 2016-6-5 9:54:44 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TbUserPermission generated by hbm2java
 */
public class TbUserPermission implements java.io.Serializable {

	private Long id;
	private Long receiveUserId;
	private Long knowledgeId;
	private Long sendUserId;
	private Integer type;
	private String mento;
	private Date createtime;
	private Short columnType;
	private Long columnId;
	private Integer ispush;

	public TbUserPermission() {
	}

	public TbUserPermission(Long receiveUserId, Long knowledgeId, Long sendUserId, Integer type, String mento,
			Date createtime, Short columnType, Long columnId, Integer ispush) {
		this.receiveUserId = receiveUserId;
		this.knowledgeId = knowledgeId;
		this.sendUserId = sendUserId;
		this.type = type;
		this.mento = mento;
		this.createtime = createtime;
		this.columnType = columnType;
		this.columnId = columnId;
		this.ispush = ispush;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getReceiveUserId() {
		return this.receiveUserId;
	}

	public void setReceiveUserId(Long receiveUserId) {
		this.receiveUserId = receiveUserId;
	}

	public Long getKnowledgeId() {
		return this.knowledgeId;
	}

	public void setKnowledgeId(Long knowledgeId) {
		this.knowledgeId = knowledgeId;
	}

	public Long getSendUserId() {
		return this.sendUserId;
	}

	public void setSendUserId(Long sendUserId) {
		this.sendUserId = sendUserId;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getMento() {
		return this.mento;
	}

	public void setMento(String mento) {
		this.mento = mento;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Short getColumnType() {
		return this.columnType;
	}

	public void setColumnType(Short columnType) {
		this.columnType = columnType;
	}

	public Long getColumnId() {
		return this.columnId;
	}

	public void setColumnId(Long columnId) {
		this.columnId = columnId;
	}

	public Integer getIspush() {
		return this.ispush;
	}

	public void setIspush(Integer ispush) {
		this.ispush = ispush;
	}

}
