package gintong.demand.old.vo;
// Generated 2016-5-25 14:28:32 by Hibernate Tools 4.3.1.Final

/**
 * C3p0test generated by hbm2java
 */
public class C3p0test implements java.io.Serializable {

	private Character a;

	public C3p0test() {
	}

	public C3p0test(Character a) {
		this.a = a;
	}

	public Character getA() {
		return this.a;
	}

	public void setA(Character a) {
		this.a = a;
	}

}
