package gintong.demand.old.vo;
// Generated 2016-5-25 14:28:32 by Hibernate Tools 4.3.1.Final

/**
 * TbDemandCount generated by hbm2java
 */
public class TbDemandCount implements java.io.Serializable {

	private Long id;
	private Long demandId;
	private Long readCount;
	private Long shareCount;
	private Long collectCount;
	private Long evaluateCount;
	private Long demandType;

	public TbDemandCount() {
	}

	public TbDemandCount(Long demandId, Long readCount, Long shareCount, Long collectCount, Long evaluateCount,
			Long demandType) {
		this.demandId = demandId;
		this.readCount = readCount;
		this.shareCount = shareCount;
		this.collectCount = collectCount;
		this.evaluateCount = evaluateCount;
		this.demandType = demandType;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getDemandId() {
		return this.demandId;
	}

	public void setDemandId(Long demandId) {
		this.demandId = demandId;
	}

	public Long getReadCount() {
		return this.readCount;
	}

	public void setReadCount(Long readCount) {
		this.readCount = readCount;
	}

	public Long getShareCount() {
		return this.shareCount;
	}

	public void setShareCount(Long shareCount) {
		this.shareCount = shareCount;
	}

	public Long getCollectCount() {
		return this.collectCount;
	}

	public void setCollectCount(Long collectCount) {
		this.collectCount = collectCount;
	}

	public Long getEvaluateCount() {
		return this.evaluateCount;
	}

	public void setEvaluateCount(Long evaluateCount) {
		this.evaluateCount = evaluateCount;
	}

	public Long getDemandType() {
		return this.demandType;
	}

	public void setDemandType(Long demandType) {
		this.demandType = demandType;
	}

}
