package gintong.demand.old.vo;
// Generated 2016-5-25 14:28:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TbUserTag generated by hbm2java
 */
public class TbUserTag implements java.io.Serializable {

	private Long id;
	private Long userId;
	private String tag;
	private Date ctime;

	public TbUserTag() {
	}

	public TbUserTag(Date ctime) {
		this.ctime = ctime;
	}

	public TbUserTag(Long userId, String tag, Date ctime) {
		this.userId = userId;
		this.tag = tag;
		this.ctime = ctime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

}
