package gintong.tagsTest.now.vo;
// Generated 2016-5-25 14:34:27 by Hibernate Tools 4.3.1.Final

/**
 * TbTag generated by hbm2java
 */
public class TbTag implements java.io.Serializable {

	private long id;
	private long userId;
	private long appId;
	private long tagType;
	private String tagName;

	public TbTag() {
	}

	public TbTag(long id, long userId, long appId, String tagName) {
		this.id = id;
		this.userId = userId;
		this.appId = appId;
		this.tagName = tagName;
	}

	public TbTag(long id, long userId, long appId, long tagType, String tagName) {
		this.id = id;
		this.userId = userId;
		this.appId = appId;
		this.tagType = tagType;
		this.tagName = tagName;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getAppId() {
		return this.appId;
	}

	public void setAppId(long appId) {
		this.appId = appId;
	}

	public long getTagType() {
		return this.tagType;
	}

	public void setTagType(long tagType) {
		this.tagType = tagType;
	}

	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

}
