package gintong.phoenix.knowledge.test.now.vo;
// Generated 2016-6-1 11:07:15 by Hibernate Tools 4.3.1.Final

/**
 * TbKnowledgeReference generated by hbm2java
 */
public class TbKnowledgeReference implements java.io.Serializable {

	private Long id;
	private Long knowledgeId;
	private String articleName;
	private String url;
	private String websiteName;
	private Character status;
	private long createDate;
	private long refDate;
	private long modifyDate;

	public TbKnowledgeReference() {
	}

	public TbKnowledgeReference(long createDate, long refDate, long modifyDate) {
		this.createDate = createDate;
		this.refDate = refDate;
		this.modifyDate = modifyDate;
	}

	public TbKnowledgeReference(Long knowledgeId, String articleName, String url, String websiteName, Character status,
			long createDate, long refDate, long modifyDate) {
		this.knowledgeId = knowledgeId;
		this.articleName = articleName;
		this.url = url;
		this.websiteName = websiteName;
		this.status = status;
		this.createDate = createDate;
		this.refDate = refDate;
		this.modifyDate = modifyDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getKnowledgeId() {
		return this.knowledgeId;
	}

	public void setKnowledgeId(Long knowledgeId) {
		this.knowledgeId = knowledgeId;
	}

	public String getArticleName() {
		return this.articleName;
	}

	public void setArticleName(String articleName) {
		this.articleName = articleName;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getWebsiteName() {
		return this.websiteName;
	}

	public void setWebsiteName(String websiteName) {
		this.websiteName = websiteName;
	}

	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public long getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(long createDate) {
		this.createDate = createDate;
	}

	public long getRefDate() {
		return this.refDate;
	}

	public void setRefDate(long refDate) {
		this.refDate = refDate;
	}

	public long getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(long modifyDate) {
		this.modifyDate = modifyDate;
	}

}
