package gintong.phoenix.knowledge.test.now.vo;
// Generated 2016-6-1 11:07:15 by Hibernate Tools 4.3.1.Final

/**
 * TbKnowledgeCountId generated by hbm2java
 */
public class TbKnowledgeCountId implements java.io.Serializable {

	private long id;
	private long knowledgeId;
	private long hotNum;

	public TbKnowledgeCountId() {
	}

	public TbKnowledgeCountId(long id, long knowledgeId, long hotNum) {
		this.id = id;
		this.knowledgeId = knowledgeId;
		this.hotNum = hotNum;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getKnowledgeId() {
		return this.knowledgeId;
	}

	public void setKnowledgeId(long knowledgeId) {
		this.knowledgeId = knowledgeId;
	}

	public long getHotNum() {
		return this.hotNum;
	}

	public void setHotNum(long hotNum) {
		this.hotNum = hotNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbKnowledgeCountId))
			return false;
		TbKnowledgeCountId castOther = (TbKnowledgeCountId) other;

		return (this.getId() == castOther.getId()) && (this.getKnowledgeId() == castOther.getKnowledgeId())
				&& (this.getHotNum() == castOther.getHotNum());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (int) this.getKnowledgeId();
		result = 37 * result + (int) this.getHotNum();
		return result;
	}

}
