package gintong.phoenix.knowledge.test.now.vo;
// Generated 2016-6-1 11:07:15 by Hibernate Tools 4.3.1.Final

/**
 * TbKnowledgeCount generated by hbm2java
 */
public class TbKnowledgeCount implements java.io.Serializable {

	private Long id;
	private Long commentCount;
	private Long shareCount;
	private Long collectCount;
	private Long clickCount;
	private Long hotCount;     
	private Long userId;        
	private Short source;
	private Short type;

	public TbKnowledgeCount() {
	}

	public TbKnowledgeCount(Long id) {
		this.id = id;
	}

	public TbKnowledgeCount(Long id, Long commentCount, Long shareCount, Long collectCount, Long clickCount,Long hotCount,
                Long userId,Short source, Short type) {
		this.id = id;
		this.commentCount = commentCount;
		this.shareCount = shareCount;
		this.collectCount = collectCount;
		this.clickCount = clickCount;
                this.hotCount = hotCount;
                this.userId = userId;
		this.source = source;
		this.type = type;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCommentCount() {
		return this.commentCount;
	}

	public void setCommentCount(Long commentCount) {
		this.commentCount = commentCount;
	}

	public Long getShareCount() {
		return this.shareCount;
	}

	public void setShareCount(Long shareCount) {
		this.shareCount = shareCount;
	}

	public Long getCollectCount() {
		return this.collectCount;
	}

	public void setCollectCount(Long collectCount) {
		this.collectCount = collectCount;
	}

	public Long getClickCount() {
		return this.clickCount;
	}

	public void setClickCount(Long clickCount) {
		this.clickCount = clickCount;
	}   
        
	public long getHotCount() {
		return this.hotCount;
	}

	public void setHotCount(long hotCount) {
		this.hotCount = hotCount;
	}        
        
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}          

	public Short getSource() {
		return this.source;
	}

	public void setSource(Short source) {
		this.source = source;
	}

	public Short getType() {
		return this.type;
	}

	public void setType(Short type) {
		this.type = type;
	}

}
