package gintong.phoenix.knowledge.test.now.vo;
// Generated 2016-6-4 21:28:47 by Hibernate Tools 4.3.1.Final

/**
 * TbKnowledgeBase generated by hbm2java
 */
public class TbKnowledgeBase implements java.io.Serializable {

	private Long id;
	private long knowledgeId;
	private Long createUserId;
	private String createUserName;
	private Long columnId;
	private Byte type;
	private String source;
	private String contentDesc;
	private String title;
	private Character essence;
	private Byte visible;
	private Long publicDate;
	private Long modifyDate;
	private Byte auditStatus;
	private boolean status;
	private Byte reportStatus;
	private long createDate;
	private Integer attachmentId;
	private String pictureId;
	private String tags;
	private String content;
	private Integer modifyUserId;
	private String modifyUserName;
	private Byte userStar;
	private Boolean isOld;

	public TbKnowledgeBase() {
	}

	public TbKnowledgeBase(long knowledgeId, boolean status, long createDate) {
		this.knowledgeId = knowledgeId;
		this.status = status;
		this.createDate = createDate;
	}

	public TbKnowledgeBase(long knowledgeId, Long createUserId, String createUserName, Long columnId, Byte type,
			String source, String contentDesc, String title, Character essence, Byte visible, Long publicDate,
			Long modifyDate, Byte auditStatus, boolean status, Byte reportStatus, long createDate,
			Integer attachmentId, String pictureId, String tags, String content, Integer modifyUserId,
			String modifyUserName, Byte userStar, Boolean isOld) {
		this.knowledgeId = knowledgeId;
		this.createUserId = createUserId;
		this.createUserName = createUserName;
		this.columnId = columnId;
		this.type = type;
		this.source = source;
		this.contentDesc = contentDesc;
		this.title = title;
		this.essence = essence;
		this.visible = visible;
		this.publicDate = publicDate;
		this.modifyDate = modifyDate;
		this.auditStatus = auditStatus;
		this.status = status;
		this.reportStatus = reportStatus;
		this.createDate = createDate;
		this.attachmentId = attachmentId;
		this.pictureId = pictureId;
		this.tags = tags;
		this.content = content;
		this.modifyUserId = modifyUserId;
		this.modifyUserName = modifyUserName;
		this.userStar = userStar;
		this.isOld = isOld;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getKnowledgeId() {
		return this.knowledgeId;
	}

	public void setKnowledgeId(long knowledgeId) {
		this.knowledgeId = knowledgeId;
	}

	public Long getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(Long createUserId) {
		this.createUserId = createUserId;
	}

	public String getCreateUserName() {
		return this.createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	public Long getColumnId() {
		return this.columnId;
	}

	public void setColumnId(Long columnId) {
		this.columnId = columnId;
	}

	public Byte getType() {
		return this.type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getContentDesc() {
		return this.contentDesc;
	}

	public void setContentDesc(String contentDesc) {
		this.contentDesc = contentDesc;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Character getEssence() {
		return this.essence;
	}

	public void setEssence(Character essence) {
		this.essence = essence;
	}

	public Byte getVisible() {
		return this.visible;
	}

	public void setVisible(Byte visible) {
		this.visible = visible;
	}

	public Long getPublicDate() {
		return this.publicDate;
	}

	public void setPublicDate(Long publicDate) {
		this.publicDate = publicDate;
	}

	public Long getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Long modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Byte getAuditStatus() {
		return this.auditStatus;
	}

	public void setAuditStatus(Byte auditStatus) {
		this.auditStatus = auditStatus;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public Byte getReportStatus() {
		return this.reportStatus;
	}

	public void setReportStatus(Byte reportStatus) {
		this.reportStatus = reportStatus;
	}

	public long getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(long createDate) {
		this.createDate = createDate;
	}

	public Integer getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(Integer attachmentId) {
		this.attachmentId = attachmentId;
	}

	public String getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(String pictureId) {
		this.pictureId = pictureId;
	}

	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getModifyUserId() {
		return this.modifyUserId;
	}

	public void setModifyUserId(Integer modifyUserId) {
		this.modifyUserId = modifyUserId;
	}

	public String getModifyUserName() {
		return this.modifyUserName;
	}

	public void setModifyUserName(String modifyUserName) {
		this.modifyUserName = modifyUserName;
	}

	public Byte getUserStar() {
		return this.userStar;
	}

	public void setUserStar(Byte userStar) {
		this.userStar = userStar;
	}

	public Boolean getIsOld() {
		return this.isOld;
	}

	public void setIsOld(Boolean isOld) {
		this.isOld = isOld;
	}

}
