package gintong.phoenix.knowledge.test.now.vo;
// Generated 2016-6-1 11:07:15 by Hibernate Tools 4.3.1.Final

/**
 * TbKnowledgeCount generated by hbm2java
 */
public class TbKnowledgeCount implements java.io.Serializable {

	private TbKnowledgeCountId id;
	private Long commentNum;
	private Long shareNum;
	private Long collectNum;
	private Long clickNum;
	private Short source;
	private Short type;

	public TbKnowledgeCount() {
	}

	public TbKnowledgeCount(TbKnowledgeCountId id) {
		this.id = id;
	}

	public TbKnowledgeCount(TbKnowledgeCountId id, Long commentNum, Long shareNum, Long collectNum, Long clickNum,
			Short source, Short type) {
		this.id = id;
		this.commentNum = commentNum;
		this.shareNum = shareNum;
		this.collectNum = collectNum;
		this.clickNum = clickNum;
		this.source = source;
		this.type = type;
	}

	public TbKnowledgeCountId getId() {
		return this.id;
	}

	public void setId(TbKnowledgeCountId id) {
		this.id = id;
	}

	public Long getCommentNum() {
		return this.commentNum;
	}

	public void setCommentNum(Long commentNum) {
		this.commentNum = commentNum;
	}

	public Long getShareNum() {
		return this.shareNum;
	}

	public void setShareNum(Long shareNum) {
		this.shareNum = shareNum;
	}

	public Long getCollectNum() {
		return this.collectNum;
	}

	public void setCollectNum(Long collectNum) {
		this.collectNum = collectNum;
	}

	public Long getClickNum() {
		return this.clickNum;
	}

	public void setClickNum(Long clickNum) {
		this.clickNum = clickNum;
	}

	public Short getSource() {
		return this.source;
	}

	public void setSource(Short source) {
		this.source = source;
	}

	public Short getType() {
		return this.type;
	}

	public void setType(Short type) {
		this.type = type;
	}

}
