package gintong.parasol.metadata.vo;
// Generated 2016-6-2 19:11:41 by Hibernate Tools 4.3.1.Final

/**
 * TbCode generated by hbm2java
 */
public class TbCode implements java.io.Serializable {

	private Long id;
	private long pid;
	private String name;
	private String numberCode;
	private String nameIndex;
	private String nameIndexAll;
	private String remark;
	private String isRoot;
	private Integer levelType;
	private Integer useType;
	private Integer orderNo;
	private Long creator;
	private Long ctime;
	private String createBy;
	private Integer hasChild;
	private Integer disabled;

	public TbCode() {
	}

	public TbCode(long pid) {
		this.pid = pid;
	}

	public TbCode(long pid, String name, String numberCode, String nameIndex, String nameIndexAll, String remark,
			String isRoot, Integer levelType, Integer useType, Integer orderNo, Long creator, Long ctime,
			String createBy, Integer hasChild, Integer disabled) {
		this.pid = pid;
		this.name = name;
		this.numberCode = numberCode;
		this.nameIndex = nameIndex;
		this.nameIndexAll = nameIndexAll;
		this.remark = remark;
		this.isRoot = isRoot;
		this.levelType = levelType;
		this.useType = useType;
		this.orderNo = orderNo;
		this.creator = creator;
		this.ctime = ctime;
		this.createBy = createBy;
		this.hasChild = hasChild;
		this.disabled = disabled;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getPid() {
		return this.pid;
	}

	public void setPid(long pid) {
		this.pid = pid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNumberCode() {
		return this.numberCode;
	}

	public void setNumberCode(String numberCode) {
		this.numberCode = numberCode;
	}

	public String getNameIndex() {
		return this.nameIndex;
	}

	public void setNameIndex(String nameIndex) {
		this.nameIndex = nameIndex;
	}

	public String getNameIndexAll() {
		return this.nameIndexAll;
	}

	public void setNameIndexAll(String nameIndexAll) {
		this.nameIndexAll = nameIndexAll;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getIsRoot() {
		return this.isRoot;
	}

	public void setIsRoot(String isRoot) {
		this.isRoot = isRoot;
	}

	public Integer getLevelType() {
		return this.levelType;
	}

	public void setLevelType(Integer levelType) {
		this.levelType = levelType;
	}

	public Integer getUseType() {
		return this.useType;
	}

	public void setUseType(Integer useType) {
		this.useType = useType;
	}

	public Integer getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(Integer orderNo) {
		this.orderNo = orderNo;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public Long getCtime() {
		return this.ctime;
	}

	public void setCtime(Long ctime) {
		this.ctime = ctime;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Integer getHasChild() {
		return this.hasChild;
	}

	public void setHasChild(Integer hasChild) {
		this.hasChild = hasChild;
	}

	public Integer getDisabled() {
		return this.disabled;
	}

	public void setDisabled(Integer disabled) {
		this.disabled = disabled;
	}

}
