package gintong.parasol.metadata.vo;
// Generated 2016-6-2 19:11:41 by Hibernate Tools 4.3.1.Final

/**
 * TbDirectoryType generated by hbm2java
 */
public class TbDirectoryType implements java.io.Serializable {

	private long id;
	private long appId;
	private String name;
	private Long updateAt;

	public TbDirectoryType() {
	}

	public TbDirectoryType(long id, long appId, String name) {
		this.id = id;
		this.appId = appId;
		this.name = name;
	}

	public TbDirectoryType(long id, long appId, String name, Long updateAt) {
		this.id = id;
		this.appId = appId;
		this.name = name;
		this.updateAt = updateAt;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getAppId() {
		return this.appId;
	}

	public void setAppId(long appId) {
		this.appId = appId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Long updateAt) {
		this.updateAt = updateAt;
	}

}
