package gintong.parasol.associate.test.now;
// Generated 2016-5-26 15:04:05 by Hibernate Tools 4.3.1.Final

/**
 * TbAssociate generated by hbm2java
 */
public class TbAssociate implements java.io.Serializable {

	private Long id;
	private long userId;
	private long appId;
	private long sourceTypeId;
	private long sourceId;
	private String assocDesc;
	private long assocTypeId;
	private long assocId;
	private String assocTitle;
	private String assocMetadata;
	private Long createAt;

	public TbAssociate() {
	}

	public TbAssociate(long userId, long appId, long sourceTypeId, long sourceId, String assocDesc, long assocTypeId,
			long assocId, String assocTitle) {
		this.userId = userId;
		this.appId = appId;
		this.sourceTypeId = sourceTypeId;
		this.sourceId = sourceId;
		this.assocDesc = assocDesc;
		this.assocTypeId = assocTypeId;
		this.assocId = assocId;
		this.assocTitle = assocTitle;
	}

	public TbAssociate(long userId, long appId, long sourceTypeId, long sourceId, String assocDesc, long assocTypeId,
			long assocId, String assocTitle, String assocMetadata, Long createAt) {
		this.userId = userId;
		this.appId = appId;
		this.sourceTypeId = sourceTypeId;
		this.sourceId = sourceId;
		this.assocDesc = assocDesc;
		this.assocTypeId = assocTypeId;
		this.assocId = assocId;
		this.assocTitle = assocTitle;
		this.assocMetadata = assocMetadata;
		this.createAt = createAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getAppId() {
		return this.appId;
	}

	public void setAppId(long appId) {
		this.appId = appId;
	}

	public long getSourceTypeId() {
		return this.sourceTypeId;
	}

	public void setSourceTypeId(long sourceTypeId) {
		this.sourceTypeId = sourceTypeId;
	}

	public long getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(long sourceId) {
		this.sourceId = sourceId;
	}

	public String getAssocDesc() {
		return this.assocDesc;
	}

	public void setAssocDesc(String assocDesc) {
		this.assocDesc = assocDesc;
	}

	public long getAssocTypeId() {
		return this.assocTypeId;
	}

	public void setAssocTypeId(long assocTypeId) {
		this.assocTypeId = assocTypeId;
	}

	public long getAssocId() {
		return this.assocId;
	}

	public void setAssocId(long assocId) {
		this.assocId = assocId;
	}

	public String getAssocTitle() {
		return this.assocTitle;
	}

	public void setAssocTitle(String assocTitle) {
		this.assocTitle = assocTitle;
	}

	public String getAssocMetadata() {
		return this.assocMetadata;
	}

	public void setAssocMetadata(String assocMetadata) {
		this.assocMetadata = assocMetadata;
	}

	public Long getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Long createAt) {
		this.createAt = createAt;
	}

}
