package datacenterservice.vo;
// Generated 2016-3-10 11:48:31 by Hibernate Tools 4.3.1.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String code;
	private int gender;
	private int age;
	private float height;
	private float weight;
	private float bmi;
	private int systolicPressure;
	private int diastolicPressure;
	private int pulseRate;
	private int oxygen;
	private int colorBlindness;
	private String registrationDate;
	private String queryTime;
	private String extendedField1;
	private String extendedField2;
	private String extendedField3;

	public User() {
	}

	public User(String code, int gender, int age, float height, float weight, float bmi, int systolicPressure,
			int diastolicPressure, int pulseRate, int oxygen, int colorBlindness) {
		this.code = code;
		this.gender = gender;
		this.age = age;
		this.height = height;
		this.weight = weight;
		this.bmi = bmi;
		this.systolicPressure = systolicPressure;
		this.diastolicPressure = diastolicPressure;
		this.pulseRate = pulseRate;
		this.oxygen = oxygen;
		this.colorBlindness = colorBlindness;
	}

	public User(String code, int gender, int age, float height, float weight, float bmi, int systolicPressure,
			int diastolicPressure, int pulseRate, int oxygen, int colorBlindness, String registrationDate,
			String queryTime, String extendedField1, String extendedField2, String extendedField3) {
		this.code = code;
		this.gender = gender;
		this.age = age;
		this.height = height;
		this.weight = weight;
		this.bmi = bmi;
		this.systolicPressure = systolicPressure;
		this.diastolicPressure = diastolicPressure;
		this.pulseRate = pulseRate;
		this.oxygen = oxygen;
		this.colorBlindness = colorBlindness;
		this.registrationDate = registrationDate;
		this.queryTime = queryTime;
		this.extendedField1 = extendedField1;
		this.extendedField2 = extendedField2;
		this.extendedField3 = extendedField3;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public int getGender() {
		return this.gender;
	}

	public void setGender(int gender) {
		this.gender = gender;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public float getHeight() {
		return this.height;
	}

	public void setHeight(float height) {
		this.height = height;
	}

	public float getWeight() {
		return this.weight;
	}

	public void setWeight(float weight) {
		this.weight = weight;
	}

	public float getBmi() {
		return this.bmi;
	}

	public void setBmi(float bmi) {
		this.bmi = bmi;
	}

	public int getSystolicPressure() {
		return this.systolicPressure;
	}

	public void setSystolicPressure(int systolicPressure) {
		this.systolicPressure = systolicPressure;
	}

	public int getDiastolicPressure() {
		return this.diastolicPressure;
	}

	public void setDiastolicPressure(int diastolicPressure) {
		this.diastolicPressure = diastolicPressure;
	}

	public int getPulseRate() {
		return this.pulseRate;
	}

	public void setPulseRate(int pulseRate) {
		this.pulseRate = pulseRate;
	}

	public int getOxygen() {
		return this.oxygen;
	}

	public void setOxygen(int oxygen) {
		this.oxygen = oxygen;
	}

	public int getColorBlindness() {
		return this.colorBlindness;
	}

	public void setColorBlindness(int colorBlindness) {
		this.colorBlindness = colorBlindness;
	}

	public String getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(String registrationDate) {
		this.registrationDate = registrationDate;
	}

	public String getQueryTime() {
		return this.queryTime;
	}

	public void setQueryTime(String queryTime) {
		this.queryTime = queryTime;
	}

	public String getExtendedField1() {
		return this.extendedField1;
	}

	public void setExtendedField1(String extendedField1) {
		this.extendedField1 = extendedField1;
	}

	public String getExtendedField2() {
		return this.extendedField2;
	}

	public void setExtendedField2(String extendedField2) {
		this.extendedField2 = extendedField2;
	}

	public String getExtendedField3() {
		return this.extendedField3;
	}

	public void setExtendedField3(String extendedField3) {
		this.extendedField3 = extendedField3;
	}

}
