package gintong.phoenix.demand.old.vo;
// Generated 2016-5-31 14:15:04 by Hibernate Tools 4.3.1.Final

/**
 * TbDemandReport generated by hbm2java
 */
public class TbDemandReport implements java.io.Serializable {

	private Long id;
	private String content;
	private String reason;
	private Long contact;
	private Long userId;
	private String userName;
	private Long demandId;
	private String createTime;

	public TbDemandReport() {
	}

	public TbDemandReport(String content, String reason, Long contact, Long userId, String userName, Long demandId,
			String createTime) {
		this.content = content;
		this.reason = reason;
		this.contact = contact;
		this.userId = userId;
		this.userName = userName;
		this.demandId = demandId;
		this.createTime = createTime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public Long getContact() {
		return this.contact;
	}

	public void setContact(Long contact) {
		this.contact = contact;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Long getDemandId() {
		return this.demandId;
	}

	public void setDemandId(Long demandId) {
		this.demandId = demandId;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
