package gintong.phoenix.demand.old.vo;
// Generated 2016-5-31 14:15:04 by Hibernate Tools 4.3.1.Final

/**
 * TbDemandDetect generated by hbm2java
 */
public class TbDemandDetect implements java.io.Serializable {

	private Long id;
	private String industryid;
	private Long sourceId;
	private Integer ptype;
	private Integer sourceType;

	public TbDemandDetect() {
	}

	public TbDemandDetect(String industryid, Long sourceId, Integer ptype, Integer sourceType) {
		this.industryid = industryid;
		this.sourceId = sourceId;
		this.ptype = ptype;
		this.sourceType = sourceType;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getIndustryid() {
		return this.industryid;
	}

	public void setIndustryid(String industryid) {
		this.industryid = industryid;
	}

	public Long getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(Long sourceId) {
		this.sourceId = sourceId;
	}

	public Integer getPtype() {
		return this.ptype;
	}

	public void setPtype(Integer ptype) {
		this.ptype = ptype;
	}

	public Integer getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(Integer sourceType) {
		this.sourceType = sourceType;
	}

}
