package gintong.phoenix.demand.old.vo;
// Generated 2016-5-31 14:15:04 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TbUserDemandPermission generated by hbm2java
 */
public class TbUserDemandPermission implements java.io.Serializable {

	private Long id;
	private Long demandId;
	private Long sendId;
	private Long receiveId;
	private Integer demandType;
	private Date createtime;
	private Integer ptype;
	private Integer isPush;

	public TbUserDemandPermission() {
	}

	public TbUserDemandPermission(Date createtime) {
		this.createtime = createtime;
	}

	public TbUserDemandPermission(Long demandId, Long sendId, Long receiveId, Integer demandType, Date createtime,
			Integer ptype, Integer isPush) {
		this.demandId = demandId;
		this.sendId = sendId;
		this.receiveId = receiveId;
		this.demandType = demandType;
		this.createtime = createtime;
		this.ptype = ptype;
		this.isPush = isPush;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getDemandId() {
		return this.demandId;
	}

	public void setDemandId(Long demandId) {
		this.demandId = demandId;
	}

	public Long getSendId() {
		return this.sendId;
	}

	public void setSendId(Long sendId) {
		this.sendId = sendId;
	}

	public Long getReceiveId() {
		return this.receiveId;
	}

	public void setReceiveId(Long receiveId) {
		this.receiveId = receiveId;
	}

	public Integer getDemandType() {
		return this.demandType;
	}

	public void setDemandType(Integer demandType) {
		this.demandType = demandType;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Integer getPtype() {
		return this.ptype;
	}

	public void setPtype(Integer ptype) {
		this.ptype = ptype;
	}

	public Integer getIsPush() {
		return this.isPush;
	}

	public void setIsPush(Integer isPush) {
		this.isPush = isPush;
	}

}
