package gintong.phoenix.demand.old.vo;
// Generated 2016-5-31 14:15:04 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TbUserCategory generated by hbm2java
 */
public class TbUserCategory implements java.io.Serializable {

	private Long id;
	private Long userId;
	private String categoryName;
	private String sortId;
	private Date ctime;
	private Long parentId;

	public TbUserCategory() {
	}

	public TbUserCategory(Date ctime) {
		this.ctime = ctime;
	}

	public TbUserCategory(Long userId, String categoryName, String sortId, Date ctime, Long parentId) {
		this.userId = userId;
		this.categoryName = categoryName;
		this.sortId = sortId;
		this.ctime = ctime;
		this.parentId = parentId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getSortId() {
		return this.sortId;
	}

	public void setSortId(String sortId) {
		this.sortId = sortId;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

}
