package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * C3p0test generated by hbm2java
 */
public class C3p0test implements java.io.Serializable {

	private Character a;

	public C3p0test() {
	}

	public C3p0test(Character a) {
		this.a = a;
	}

	public Character getA() {
		return this.a;
	}

	public void setA(Character a) {
		this.a = a;
	}

}
