package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbActivityEnter generated by hbm2java
 */
public class TbActivityEnter implements java.io.Serializable {

	private Long id;
	private Long userId;
	private String userName;
	private String mobile;
	private String email;
	private String corporation;
	private String job;
	private String ctime;
	private Integer status;
	private String intent;
	private Long activityId;

	public TbActivityEnter() {
	}

	public TbActivityEnter(Long userId, String userName, String mobile, String email, String corporation, String job,
			String ctime, Integer status, String intent, Long activityId) {
		this.userId = userId;
		this.userName = userName;
		this.mobile = mobile;
		this.email = email;
		this.corporation = corporation;
		this.job = job;
		this.ctime = ctime;
		this.status = status;
		this.intent = intent;
		this.activityId = activityId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCorporation() {
		return this.corporation;
	}

	public void setCorporation(String corporation) {
		this.corporation = corporation;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getCtime() {
		return this.ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getIntent() {
		return this.intent;
	}

	public void setIntent(String intent) {
		this.intent = intent;
	}

	public Long getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Long activityId) {
		this.activityId = activityId;
	}

}
