package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbActivity generated by hbm2java
 */
public class TbActivity implements java.io.Serializable {

	private Long id;
	private String title;
	private String summary;
	private String ctime;
	private Integer status;

	public TbActivity() {
	}

	public TbActivity(String title, String summary, String ctime, Integer status) {
		this.title = title;
		this.summary = summary;
		this.ctime = ctime;
		this.status = status;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getCtime() {
		return this.ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
