package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbActivityManager generated by hbm2java
 */
public class TbActivityManager implements java.io.Serializable {

	private Long id;
	private Integer activityId;
	private Integer managerId;

	public TbActivityManager() {
	}

	public TbActivityManager(Integer activityId, Integer managerId) {
		this.activityId = activityId;
		this.managerId = managerId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	public Integer getManagerId() {
		return this.managerId;
	}

	public void setManagerId(Integer managerId) {
		this.managerId = managerId;
	}

}
