package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * TbCorporation generated by hbm2java
 */
public class TbCorporation implements java.io.Serializable {

	private Long id;
	private String name;
	private String url;
	private Long parentId;
	private Date ctime;
	private Date utime;
	private String number;
	private String shortName;
	private String license;
	private String licenseCountry;
	private String licenseProvince;
	private String licenseCity;
	private String licenseTown;
	private String orgCode;
	private String address;
	private String areaCode;
	private String phone;
	private String extension;
	private String bank;
	private String account;
	private String licensePic;
	private String linkName;
	private String linkGender;
	private String linkMobile;
	private String linkIdcard;
	private String linkIdPic;
	private String legalName;
	private String legalIdcard;
	private String legalMobile;
	private String legalIdPic;
	private Long belong;
	private Long typeId;
	private String type;
	private String industryIds;
	private String industryNames;
	private Byte auth;
	private String accredit;
	private String addition;

	public TbCorporation() {
	}

	public TbCorporation(String name, String url, Long parentId, Date ctime, Date utime, String number,
			String shortName, String license, String licenseCountry, String licenseProvince, String licenseCity,
			String licenseTown, String orgCode, String address, String areaCode, String phone, String extension,
			String bank, String account, String licensePic, String linkName, String linkGender, String linkMobile,
			String linkIdcard, String linkIdPic, String legalName, String legalIdcard, String legalMobile,
			String legalIdPic, Long belong, Long typeId, String type, String industryIds, String industryNames,
			Byte auth, String accredit, String addition) {
		this.name = name;
		this.url = url;
		this.parentId = parentId;
		this.ctime = ctime;
		this.utime = utime;
		this.number = number;
		this.shortName = shortName;
		this.license = license;
		this.licenseCountry = licenseCountry;
		this.licenseProvince = licenseProvince;
		this.licenseCity = licenseCity;
		this.licenseTown = licenseTown;
		this.orgCode = orgCode;
		this.address = address;
		this.areaCode = areaCode;
		this.phone = phone;
		this.extension = extension;
		this.bank = bank;
		this.account = account;
		this.licensePic = licensePic;
		this.linkName = linkName;
		this.linkGender = linkGender;
		this.linkMobile = linkMobile;
		this.linkIdcard = linkIdcard;
		this.linkIdPic = linkIdPic;
		this.legalName = legalName;
		this.legalIdcard = legalIdcard;
		this.legalMobile = legalMobile;
		this.legalIdPic = legalIdPic;
		this.belong = belong;
		this.typeId = typeId;
		this.type = type;
		this.industryIds = industryIds;
		this.industryNames = industryNames;
		this.auth = auth;
		this.accredit = accredit;
		this.addition = addition;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getLicense() {
		return this.license;
	}

	public void setLicense(String license) {
		this.license = license;
	}

	public String getLicenseCountry() {
		return this.licenseCountry;
	}

	public void setLicenseCountry(String licenseCountry) {
		this.licenseCountry = licenseCountry;
	}

	public String getLicenseProvince() {
		return this.licenseProvince;
	}

	public void setLicenseProvince(String licenseProvince) {
		this.licenseProvince = licenseProvince;
	}

	public String getLicenseCity() {
		return this.licenseCity;
	}

	public void setLicenseCity(String licenseCity) {
		this.licenseCity = licenseCity;
	}

	public String getLicenseTown() {
		return this.licenseTown;
	}

	public void setLicenseTown(String licenseTown) {
		this.licenseTown = licenseTown;
	}

	public String getOrgCode() {
		return this.orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getLicensePic() {
		return this.licensePic;
	}

	public void setLicensePic(String licensePic) {
		this.licensePic = licensePic;
	}

	public String getLinkName() {
		return this.linkName;
	}

	public void setLinkName(String linkName) {
		this.linkName = linkName;
	}

	public String getLinkGender() {
		return this.linkGender;
	}

	public void setLinkGender(String linkGender) {
		this.linkGender = linkGender;
	}

	public String getLinkMobile() {
		return this.linkMobile;
	}

	public void setLinkMobile(String linkMobile) {
		this.linkMobile = linkMobile;
	}

	public String getLinkIdcard() {
		return this.linkIdcard;
	}

	public void setLinkIdcard(String linkIdcard) {
		this.linkIdcard = linkIdcard;
	}

	public String getLinkIdPic() {
		return this.linkIdPic;
	}

	public void setLinkIdPic(String linkIdPic) {
		this.linkIdPic = linkIdPic;
	}

	public String getLegalName() {
		return this.legalName;
	}

	public void setLegalName(String legalName) {
		this.legalName = legalName;
	}

	public String getLegalIdcard() {
		return this.legalIdcard;
	}

	public void setLegalIdcard(String legalIdcard) {
		this.legalIdcard = legalIdcard;
	}

	public String getLegalMobile() {
		return this.legalMobile;
	}

	public void setLegalMobile(String legalMobile) {
		this.legalMobile = legalMobile;
	}

	public String getLegalIdPic() {
		return this.legalIdPic;
	}

	public void setLegalIdPic(String legalIdPic) {
		this.legalIdPic = legalIdPic;
	}

	public Long getBelong() {
		return this.belong;
	}

	public void setBelong(Long belong) {
		this.belong = belong;
	}

	public Long getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getIndustryIds() {
		return this.industryIds;
	}

	public void setIndustryIds(String industryIds) {
		this.industryIds = industryIds;
	}

	public String getIndustryNames() {
		return this.industryNames;
	}

	public void setIndustryNames(String industryNames) {
		this.industryNames = industryNames;
	}

	public Byte getAuth() {
		return this.auth;
	}

	public void setAuth(Byte auth) {
		this.auth = auth;
	}

	public String getAccredit() {
		return this.accredit;
	}

	public void setAccredit(String accredit) {
		this.accredit = accredit;
	}

	public String getAddition() {
		return this.addition;
	}

	public void setAddition(String addition) {
		this.addition = addition;
	}

}
