package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbCorporationType generated by hbm2java
 */
public class TbCorporationType implements java.io.Serializable {

	private Long id;
	private String name;
	private String type;
	private Integer level;
	private Long creator;
	private String ctime;
	private Integer useType;
	private String nameIndex;
	private String nameIndexAll;
	private Long useCount;
	private Integer root;
	private Integer industry;
	private String number;
	private Long sysItemId;
	private String sysItem;
	private Integer orderNo;
	private String createBy;
	private String remark;
	private Integer hasChild;
	private Integer mold;

	public TbCorporationType() {
	}

	public TbCorporationType(String name, String type, Integer level, Long creator, String ctime, Integer useType,
			String nameIndex, String nameIndexAll, Long useCount, Integer root, Integer industry, String number,
			Long sysItemId, String sysItem, Integer orderNo, String createBy, String remark, Integer hasChild,
			Integer mold) {
		this.name = name;
		this.type = type;
		this.level = level;
		this.creator = creator;
		this.ctime = ctime;
		this.useType = useType;
		this.nameIndex = nameIndex;
		this.nameIndexAll = nameIndexAll;
		this.useCount = useCount;
		this.root = root;
		this.industry = industry;
		this.number = number;
		this.sysItemId = sysItemId;
		this.sysItem = sysItem;
		this.orderNo = orderNo;
		this.createBy = createBy;
		this.remark = remark;
		this.hasChild = hasChild;
		this.mold = mold;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Long getCreator() {
		return this.creator;
	}

	public void setCreator(Long creator) {
		this.creator = creator;
	}

	public String getCtime() {
		return this.ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

	public Integer getUseType() {
		return this.useType;
	}

	public void setUseType(Integer useType) {
		this.useType = useType;
	}

	public String getNameIndex() {
		return this.nameIndex;
	}

	public void setNameIndex(String nameIndex) {
		this.nameIndex = nameIndex;
	}

	public String getNameIndexAll() {
		return this.nameIndexAll;
	}

	public void setNameIndexAll(String nameIndexAll) {
		this.nameIndexAll = nameIndexAll;
	}

	public Long getUseCount() {
		return this.useCount;
	}

	public void setUseCount(Long useCount) {
		this.useCount = useCount;
	}

	public Integer getRoot() {
		return this.root;
	}

	public void setRoot(Integer root) {
		this.root = root;
	}

	public Integer getIndustry() {
		return this.industry;
	}

	public void setIndustry(Integer industry) {
		this.industry = industry;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Long getSysItemId() {
		return this.sysItemId;
	}

	public void setSysItemId(Long sysItemId) {
		this.sysItemId = sysItemId;
	}

	public String getSysItem() {
		return this.sysItem;
	}

	public void setSysItem(String sysItem) {
		this.sysItem = sysItem;
	}

	public Integer getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(Integer orderNo) {
		this.orderNo = orderNo;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getHasChild() {
		return this.hasChild;
	}

	public void setHasChild(Integer hasChild) {
		this.hasChild = hasChild;
	}

	public Integer getMold() {
		return this.mold;
	}

	public void setMold(Integer mold) {
		this.mold = mold;
	}

}
