package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * TbCodeDy generated by hbm2java
 */
public class TbCodeDy implements java.io.Serializable {

	private Long id;
	private String name;
	private Date ctime;

	public TbCodeDy() {
	}

	public TbCodeDy(String name, Date ctime) {
		this.name = name;
		this.ctime = ctime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

}
