package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbCorporationVisit generated by hbm2java
 */
public class TbCorporationVisit implements java.io.Serializable {

	private Long id;
	private Long orgId;
	private Long userId;
	private String ctime;

	public TbCorporationVisit() {
	}

	public TbCorporationVisit(Long orgId, Long userId, String ctime) {
		this.orgId = orgId;
		this.userId = userId;
		this.ctime = ctime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getCtime() {
		return this.ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

}
