package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbCorporationConfig generated by hbm2java
 */
public class TbCorporationConfig implements java.io.Serializable {

	private long id;
	private Integer license;
	private Integer licenseProvince;
	private Integer orgCode;
	private Integer address;
	private Integer phone;
	private Integer bank;
	private Integer account;
	private Integer licensePic;
	private Integer legalName;
	private Integer legalIdcard;
	private Integer legalMobile;
	private Integer legalIdPic;

	public TbCorporationConfig() {
	}

	public TbCorporationConfig(long id) {
		this.id = id;
	}

	public TbCorporationConfig(long id, Integer license, Integer licenseProvince, Integer orgCode, Integer address,
			Integer phone, Integer bank, Integer account, Integer licensePic, Integer legalName, Integer legalIdcard,
			Integer legalMobile, Integer legalIdPic) {
		this.id = id;
		this.license = license;
		this.licenseProvince = licenseProvince;
		this.orgCode = orgCode;
		this.address = address;
		this.phone = phone;
		this.bank = bank;
		this.account = account;
		this.licensePic = licensePic;
		this.legalName = legalName;
		this.legalIdcard = legalIdcard;
		this.legalMobile = legalMobile;
		this.legalIdPic = legalIdPic;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Integer getLicense() {
		return this.license;
	}

	public void setLicense(Integer license) {
		this.license = license;
	}

	public Integer getLicenseProvince() {
		return this.licenseProvince;
	}

	public void setLicenseProvince(Integer licenseProvince) {
		this.licenseProvince = licenseProvince;
	}

	public Integer getOrgCode() {
		return this.orgCode;
	}

	public void setOrgCode(Integer orgCode) {
		this.orgCode = orgCode;
	}

	public Integer getAddress() {
		return this.address;
	}

	public void setAddress(Integer address) {
		this.address = address;
	}

	public Integer getPhone() {
		return this.phone;
	}

	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	public Integer getBank() {
		return this.bank;
	}

	public void setBank(Integer bank) {
		this.bank = bank;
	}

	public Integer getAccount() {
		return this.account;
	}

	public void setAccount(Integer account) {
		this.account = account;
	}

	public Integer getLicensePic() {
		return this.licensePic;
	}

	public void setLicensePic(Integer licensePic) {
		this.licensePic = licensePic;
	}

	public Integer getLegalName() {
		return this.legalName;
	}

	public void setLegalName(Integer legalName) {
		this.legalName = legalName;
	}

	public Integer getLegalIdcard() {
		return this.legalIdcard;
	}

	public void setLegalIdcard(Integer legalIdcard) {
		this.legalIdcard = legalIdcard;
	}

	public Integer getLegalMobile() {
		return this.legalMobile;
	}

	public void setLegalMobile(Integer legalMobile) {
		this.legalMobile = legalMobile;
	}

	public Integer getLegalIdPic() {
		return this.legalIdPic;
	}

	public void setLegalIdPic(Integer legalIdPic) {
		this.legalIdPic = legalIdPic;
	}

}
