package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbDiaryLog generated by hbm2java
 */
public class TbDiaryLog implements java.io.Serializable {

	private Long id;
	private Long diaryId;
	private String content;
	private Integer type;
	private String result;
	private String reason;
	private String ctime;
	private Long creatorId;
	private String creator;

	public TbDiaryLog() {
	}

	public TbDiaryLog(Long diaryId, String content, Integer type, String result, String reason, String ctime,
			Long creatorId, String creator) {
		this.diaryId = diaryId;
		this.content = content;
		this.type = type;
		this.result = result;
		this.reason = reason;
		this.ctime = ctime;
		this.creatorId = creatorId;
		this.creator = creator;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getDiaryId() {
		return this.diaryId;
	}

	public void setDiaryId(Long diaryId) {
		this.diaryId = diaryId;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getCtime() {
		return this.ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

}
