package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbDiaryRelation generated by hbm2java
 */
public class TbDiaryRelation implements java.io.Serializable {

	private Long id;
	private Long diaryId;
	private Long fbrId;
	private Long replyId1;
	private Long replyId2;
	private Long parentId;
	private Long userOneId;
	private String userOneName;
	private Long userTwoId;
	private String userTwoName;
	private String ctime;
	private Integer type;
	private Integer userStatus;
	private String content;
	private Integer delstatus;

	public TbDiaryRelation() {
	}

	public TbDiaryRelation(Long diaryId, Long fbrId, Long replyId1, Long replyId2, Long parentId, Long userOneId,
			String userOneName, Long userTwoId, String userTwoName, String ctime, Integer type, Integer userStatus,
			String content, Integer delstatus) {
		this.diaryId = diaryId;
		this.fbrId = fbrId;
		this.replyId1 = replyId1;
		this.replyId2 = replyId2;
		this.parentId = parentId;
		this.userOneId = userOneId;
		this.userOneName = userOneName;
		this.userTwoId = userTwoId;
		this.userTwoName = userTwoName;
		this.ctime = ctime;
		this.type = type;
		this.userStatus = userStatus;
		this.content = content;
		this.delstatus = delstatus;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getDiaryId() {
		return this.diaryId;
	}

	public void setDiaryId(Long diaryId) {
		this.diaryId = diaryId;
	}

	public Long getFbrId() {
		return this.fbrId;
	}

	public void setFbrId(Long fbrId) {
		this.fbrId = fbrId;
	}

	public Long getReplyId1() {
		return this.replyId1;
	}

	public void setReplyId1(Long replyId1) {
		this.replyId1 = replyId1;
	}

	public Long getReplyId2() {
		return this.replyId2;
	}

	public void setReplyId2(Long replyId2) {
		this.replyId2 = replyId2;
	}

	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public Long getUserOneId() {
		return this.userOneId;
	}

	public void setUserOneId(Long userOneId) {
		this.userOneId = userOneId;
	}

	public String getUserOneName() {
		return this.userOneName;
	}

	public void setUserOneName(String userOneName) {
		this.userOneName = userOneName;
	}

	public Long getUserTwoId() {
		return this.userTwoId;
	}

	public void setUserTwoId(Long userTwoId) {
		this.userTwoId = userTwoId;
	}

	public String getUserTwoName() {
		return this.userTwoName;
	}

	public void setUserTwoName(String userTwoName) {
		this.userTwoName = userTwoName;
	}

	public String getCtime() {
		return this.ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(Integer userStatus) {
		this.userStatus = userStatus;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getDelstatus() {
		return this.delstatus;
	}

	public void setDelstatus(Integer delstatus) {
		this.delstatus = delstatus;
	}

}
