package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbDynamicPraise generated by hbm2java
 */
public class TbDynamicPraise implements java.io.Serializable {

	private Long id;
	private long pid;
	private long dynamicId;
	private Integer ptype;

	public TbDynamicPraise() {
	}

	public TbDynamicPraise(long pid, long dynamicId) {
		this.pid = pid;
		this.dynamicId = dynamicId;
	}

	public TbDynamicPraise(long pid, long dynamicId, Integer ptype) {
		this.pid = pid;
		this.dynamicId = dynamicId;
		this.ptype = ptype;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getPid() {
		return this.pid;
	}

	public void setPid(long pid) {
		this.pid = pid;
	}

	public long getDynamicId() {
		return this.dynamicId;
	}

	public void setDynamicId(long dynamicId) {
		this.dynamicId = dynamicId;
	}

	public Integer getPtype() {
		return this.ptype;
	}

	public void setPtype(Integer ptype) {
		this.ptype = ptype;
	}

}
