package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * TbDynamicShield generated by hbm2java
 */
public class TbDynamicShield implements java.io.Serializable {

	private Long id;
	private Long userId;
	private Long shieldUserId;
	private Date ctime;

	public TbDynamicShield() {
	}

	public TbDynamicShield(Long userId, Long shieldUserId, Date ctime) {
		this.userId = userId;
		this.shieldUserId = shieldUserId;
		this.ctime = ctime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getShieldUserId() {
		return this.shieldUserId;
	}

	public void setShieldUserId(Long shieldUserId) {
		this.shieldUserId = shieldUserId;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

}
