package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * TbEvaluateApprover generated by hbm2java
 */
public class TbEvaluateApprover implements java.io.Serializable {

	private Long id;
	private Long ueid;
	private Long userId;
	private Date agreeTime;

	public TbEvaluateApprover() {
	}

	public TbEvaluateApprover(Long ueid, Long userId, Date agreeTime) {
		this.ueid = ueid;
		this.userId = userId;
		this.agreeTime = agreeTime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUeid() {
		return this.ueid;
	}

	public void setUeid(Long ueid) {
		this.ueid = ueid;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Date getAgreeTime() {
		return this.agreeTime;
	}

	public void setAgreeTime(Date agreeTime) {
		this.agreeTime = agreeTime;
	}

}
