package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbHelpMessage generated by hbm2java
 */
public class TbHelpMessage implements java.io.Serializable {

	private Long id;
	private long userId;
	private int type;
	private String remark;

	public TbHelpMessage() {
	}

	public TbHelpMessage(long userId, int type) {
		this.userId = userId;
		this.type = type;
	}

	public TbHelpMessage(long userId, int type, String remark) {
		this.userId = userId;
		this.type = type;
		this.remark = remark;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
