package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbImportCorporationInfo generated by hbm2java
 */
public class TbImportCorporationInfo implements java.io.Serializable {

	private Long id;
	private Long fileId;
	private Integer count;
	private Byte status;
	private String ctime;
	private String creator;
	private Long creatorId;

	public TbImportCorporationInfo() {
	}

	public TbImportCorporationInfo(Long fileId, Integer count, Byte status, String ctime, String creator,
			Long creatorId) {
		this.fileId = fileId;
		this.count = count;
		this.status = status;
		this.ctime = ctime;
		this.creator = creator;
		this.creatorId = creatorId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getFileId() {
		return this.fileId;
	}

	public void setFileId(Long fileId) {
		this.fileId = fileId;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public String getCtime() {
		return this.ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

}
