package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbImportCorporation generated by hbm2java
 */
public class TbImportCorporation implements java.io.Serializable {

	private Long id;
	private Long number;
	private String name;
	private Long belongId;
	private String belong;
	private String mobile;
	private String email;
	private Long typeId;
	private String type;
	private Byte status;
	private Long infoId;
	private String result;
	private String ctime;
	private String creator;
	private Long creatorId;

	public TbImportCorporation() {
	}

	public TbImportCorporation(Long number, String name, Long belongId, String belong, String mobile, String email,
			Long typeId, String type, Byte status, Long infoId, String result, String ctime, String creator,
			Long creatorId) {
		this.number = number;
		this.name = name;
		this.belongId = belongId;
		this.belong = belong;
		this.mobile = mobile;
		this.email = email;
		this.typeId = typeId;
		this.type = type;
		this.status = status;
		this.infoId = infoId;
		this.result = result;
		this.ctime = ctime;
		this.creator = creator;
		this.creatorId = creatorId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getNumber() {
		return this.number;
	}

	public void setNumber(Long number) {
		this.number = number;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getBelongId() {
		return this.belongId;
	}

	public void setBelongId(Long belongId) {
		this.belongId = belongId;
	}

	public String getBelong() {
		return this.belong;
	}

	public void setBelong(String belong) {
		this.belong = belong;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Long getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Long getInfoId() {
		return this.infoId;
	}

	public void setInfoId(Long infoId) {
		this.infoId = infoId;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getCtime() {
		return this.ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

}
