package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * TbImportContacts generated by hbm2java
 */
public class TbImportContacts implements java.io.Serializable {

	private Long id;
	private String name;
	private String email;
	private Long userId;
	private String taskId;
	private Character state;
	private Date createTime;
	private Character isSend;

	public TbImportContacts() {
	}

	public TbImportContacts(String name, String email, Long userId, String taskId, Character state, Date createTime,
			Character isSend) {
		this.name = name;
		this.email = email;
		this.userId = userId;
		this.taskId = taskId;
		this.state = state;
		this.createTime = createTime;
		this.isSend = isSend;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getTaskId() {
		return this.taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	public Character getState() {
		return this.state;
	}

	public void setState(Character state) {
		this.state = state;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Character getIsSend() {
		return this.isSend;
	}

	public void setIsSend(Character isSend) {
		this.isSend = isSend;
	}

}
