package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * TbInviteHistory generated by hbm2java
 */
public class TbInviteHistory implements java.io.Serializable {

	private Long id;
	private String inviteContent;
	private String inviteAddress;
	private String inviteUserName;
	private Character inviteType;
	private Character regStatus;
	private Character sendStatus;
	private Long sendUserId;
	private String sendUserName;
	private String sendUserMobile;
	private Date sendDate;
	private Date lastInviteDate;

	public TbInviteHistory() {
	}

	public TbInviteHistory(String inviteContent, String inviteAddress, String inviteUserName, Character inviteType,
			Character regStatus, Character sendStatus, Long sendUserId, String sendUserName, String sendUserMobile,
			Date sendDate, Date lastInviteDate) {
		this.inviteContent = inviteContent;
		this.inviteAddress = inviteAddress;
		this.inviteUserName = inviteUserName;
		this.inviteType = inviteType;
		this.regStatus = regStatus;
		this.sendStatus = sendStatus;
		this.sendUserId = sendUserId;
		this.sendUserName = sendUserName;
		this.sendUserMobile = sendUserMobile;
		this.sendDate = sendDate;
		this.lastInviteDate = lastInviteDate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getInviteContent() {
		return this.inviteContent;
	}

	public void setInviteContent(String inviteContent) {
		this.inviteContent = inviteContent;
	}

	public String getInviteAddress() {
		return this.inviteAddress;
	}

	public void setInviteAddress(String inviteAddress) {
		this.inviteAddress = inviteAddress;
	}

	public String getInviteUserName() {
		return this.inviteUserName;
	}

	public void setInviteUserName(String inviteUserName) {
		this.inviteUserName = inviteUserName;
	}

	public Character getInviteType() {
		return this.inviteType;
	}

	public void setInviteType(Character inviteType) {
		this.inviteType = inviteType;
	}

	public Character getRegStatus() {
		return this.regStatus;
	}

	public void setRegStatus(Character regStatus) {
		this.regStatus = regStatus;
	}

	public Character getSendStatus() {
		return this.sendStatus;
	}

	public void setSendStatus(Character sendStatus) {
		this.sendStatus = sendStatus;
	}

	public Long getSendUserId() {
		return this.sendUserId;
	}

	public void setSendUserId(Long sendUserId) {
		this.sendUserId = sendUserId;
	}

	public String getSendUserName() {
		return this.sendUserName;
	}

	public void setSendUserName(String sendUserName) {
		this.sendUserName = sendUserName;
	}

	public String getSendUserMobile() {
		return this.sendUserMobile;
	}

	public void setSendUserMobile(String sendUserMobile) {
		this.sendUserMobile = sendUserMobile;
	}

	public Date getSendDate() {
		return this.sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	public Date getLastInviteDate() {
		return this.lastInviteDate;
	}

	public void setLastInviteDate(Date lastInviteDate) {
		this.lastInviteDate = lastInviteDate;
	}

}
