package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbLoginThird generated by hbm2java
 */
public class TbLoginThird implements java.io.Serializable {

	private Long id;
	private String openid;
	private String accesstoken;
	private String expiresday;
	private Integer loginType;

	public TbLoginThird() {
	}

	public TbLoginThird(String openid, String accesstoken, String expiresday, Integer loginType) {
		this.openid = openid;
		this.accesstoken = accesstoken;
		this.expiresday = expiresday;
		this.loginType = loginType;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	public String getAccesstoken() {
		return this.accesstoken;
	}

	public void setAccesstoken(String accesstoken) {
		this.accesstoken = accesstoken;
	}

	public String getExpiresday() {
		return this.expiresday;
	}

	public void setExpiresday(String expiresday) {
		this.expiresday = expiresday;
	}

	public Integer getLoginType() {
		return this.loginType;
	}

	public void setLoginType(Integer loginType) {
		this.loginType = loginType;
	}

}
