package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * TbManager generated by hbm2java
 */
public class TbManager implements java.io.Serializable {

	private Long id;
	private long createdBy;
	private String createdByName;
	private Date createdTime;
	private String amount;
	private long roleId;
	private String roleName;
	private String state;
	private Date updatedTime;
	private long userId;
	private String userLogName;
	private String userName;
	private String dlm;
	private String password;
	private String sex;
	private String age;
	private String email;
	private String address;
	private String mobile;

	public TbManager() {
	}

	public TbManager(long createdBy, long roleId, long userId) {
		this.createdBy = createdBy;
		this.roleId = roleId;
		this.userId = userId;
	}

	public TbManager(long createdBy, String createdByName, Date createdTime, String amount, long roleId,
			String roleName, String state, Date updatedTime, long userId, String userLogName, String userName,
			String dlm, String password, String sex, String age, String email, String address, String mobile) {
		this.createdBy = createdBy;
		this.createdByName = createdByName;
		this.createdTime = createdTime;
		this.amount = amount;
		this.roleId = roleId;
		this.roleName = roleName;
		this.state = state;
		this.updatedTime = updatedTime;
		this.userId = userId;
		this.userLogName = userLogName;
		this.userName = userName;
		this.dlm = dlm;
		this.password = password;
		this.sex = sex;
		this.age = age;
		this.email = email;
		this.address = address;
		this.mobile = mobile;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	public String getCreatedByName() {
		return this.createdByName;
	}

	public void setCreatedByName(String createdByName) {
		this.createdByName = createdByName;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getUserLogName() {
		return this.userLogName;
	}

	public void setUserLogName(String userLogName) {
		this.userLogName = userLogName;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getDlm() {
		return this.dlm;
	}

	public void setDlm(String dlm) {
		this.dlm = dlm;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

}
