package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbPeopleDynamic generated by hbm2java
 */
public class TbPeopleDynamic implements java.io.Serializable {

	private Long id;
	private long peopleId;
	private String peopleName;
	private String mobile;
	private int status;
	private String taskId;
	private String ctime;
	private long userId;
	private Integer type;

	public TbPeopleDynamic() {
	}

	public TbPeopleDynamic(long peopleId, String mobile, int status, String taskId, long userId) {
		this.peopleId = peopleId;
		this.mobile = mobile;
		this.status = status;
		this.taskId = taskId;
		this.userId = userId;
	}

	public TbPeopleDynamic(long peopleId, String peopleName, String mobile, int status, String taskId, String ctime,
			long userId, Integer type) {
		this.peopleId = peopleId;
		this.peopleName = peopleName;
		this.mobile = mobile;
		this.status = status;
		this.taskId = taskId;
		this.ctime = ctime;
		this.userId = userId;
		this.type = type;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getPeopleId() {
		return this.peopleId;
	}

	public void setPeopleId(long peopleId) {
		this.peopleId = peopleId;
	}

	public String getPeopleName() {
		return this.peopleName;
	}

	public void setPeopleName(String peopleName) {
		this.peopleName = peopleName;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getTaskId() {
		return this.taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	public String getCtime() {
		return this.ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
