package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbPermission generated by hbm2java
 */
public class TbPermission implements java.io.Serializable {

	private Long id;
	private String name;
	private String number;
	private String remark;
	private Long parentId;

	public TbPermission() {
	}

	public TbPermission(String name, String number, String remark, Long parentId) {
		this.name = name;
		this.number = number;
		this.remark = remark;
		this.parentId = parentId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

}
