package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * TbRDelete generated by hbm2java
 */
public class TbRDelete implements java.io.Serializable {

	private TbRDeleteId id;
	private Date dtime;

	public TbRDelete() {
	}

	public TbRDelete(TbRDeleteId id) {
		this.id = id;
	}

	public TbRDelete(TbRDeleteId id, Date dtime) {
		this.id = id;
		this.dtime = dtime;
	}

	public TbRDeleteId getId() {
		return this.id;
	}

	public void setId(TbRDeleteId id) {
		this.id = id;
	}

	public Date getDtime() {
		return this.dtime;
	}

	public void setDtime(Date dtime) {
		this.dtime = dtime;
	}

}
