package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbRDeleteId generated by hbm2java
 */
public class TbRDeleteId implements java.io.Serializable {

	private long userId;
	private long targetId;
	private int targetType;

	public TbRDeleteId() {
	}

	public TbRDeleteId(long userId, long targetId, int targetType) {
		this.userId = userId;
		this.targetId = targetId;
		this.targetType = targetType;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getTargetId() {
		return this.targetId;
	}

	public void setTargetId(long targetId) {
		this.targetId = targetId;
	}

	public int getTargetType() {
		return this.targetType;
	}

	public void setTargetType(int targetType) {
		this.targetType = targetType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbRDeleteId))
			return false;
		TbRDeleteId castOther = (TbRDeleteId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getTargetId() == castOther.getTargetId())
				&& (this.getTargetType() == castOther.getTargetType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getTargetId();
		result = 37 * result + this.getTargetType();
		return result;
	}

}
