package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbRUserShield generated by hbm2java
 */
public class TbRUserShield implements java.io.Serializable {

	private Long id;
	private Long userId;
	private String deadline;
	private String startTime;
	private String endTime;
	private String reason;
	private String creator;
	private Long creatorId;
	private String ctime;
	private String utime;
	private Integer regainType;
	private String regainReason;

	public TbRUserShield() {
	}

	public TbRUserShield(Long userId, String deadline, String startTime, String endTime, String reason, String creator,
			Long creatorId, String ctime, String utime, Integer regainType, String regainReason) {
		this.userId = userId;
		this.deadline = deadline;
		this.startTime = startTime;
		this.endTime = endTime;
		this.reason = reason;
		this.creator = creator;
		this.creatorId = creatorId;
		this.ctime = ctime;
		this.utime = utime;
		this.regainType = regainType;
		this.regainReason = regainReason;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getDeadline() {
		return this.deadline;
	}

	public void setDeadline(String deadline) {
		this.deadline = deadline;
	}

	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	public String getCtime() {
		return this.ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

	public String getUtime() {
		return this.utime;
	}

	public void setUtime(String utime) {
		this.utime = utime;
	}

	public Integer getRegainType() {
		return this.regainType;
	}

	public void setRegainType(Integer regainType) {
		this.regainType = regainType;
	}

	public String getRegainReason() {
		return this.regainReason;
	}

	public void setRegainReason(String regainReason) {
		this.regainReason = regainReason;
	}

}
