package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * TbRUser generated by hbm2java
 */
public class TbRUser implements java.io.Serializable {

	private Long id;
	private Long userId;
	private Long friendId;
	private Integer status;
	private Date ctime;
	private Date utime;
	private String remark;
	private Boolean virtual;

	public TbRUser() {
	}

	public TbRUser(Long userId, Long friendId, Integer status, Date ctime, Date utime, String remark, Boolean virtual) {
		this.userId = userId;
		this.friendId = friendId;
		this.status = status;
		this.ctime = ctime;
		this.utime = utime;
		this.remark = remark;
		this.virtual = virtual;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getFriendId() {
		return this.friendId;
	}

	public void setFriendId(Long friendId) {
		this.friendId = friendId;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Boolean getVirtual() {
		return this.virtual;
	}

	public void setVirtual(Boolean virtual) {
		this.virtual = virtual;
	}

}
