package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * TbUserEvaluate generated by hbm2java
 */
public class TbUserEvaluate implements java.io.Serializable {

	private Long id;
	private String userComment;
	private Long count;
	private Long userId;
	private Long createId;
	private Date commentTime;
	private Integer userType;

	public TbUserEvaluate() {
	}

	public TbUserEvaluate(String userComment, Long count, Long userId, Long createId, Date commentTime,
			Integer userType) {
		this.userComment = userComment;
		this.count = count;
		this.userId = userId;
		this.createId = createId;
		this.commentTime = commentTime;
		this.userType = userType;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserComment() {
		return this.userComment;
	}

	public void setUserComment(String userComment) {
		this.userComment = userComment;
	}

	public Long getCount() {
		return this.count;
	}

	public void setCount(Long count) {
		this.count = count;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getCreateId() {
		return this.createId;
	}

	public void setCreateId(Long createId) {
		this.createId = createId;
	}

	public Date getCommentTime() {
		return this.commentTime;
	}

	public void setCommentTime(Date commentTime) {
		this.commentTime = commentTime;
	}

	public Integer getUserType() {
		return this.userType;
	}

	public void setUserType(Integer userType) {
		this.userType = userType;
	}

}
