package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * TbUserLog generated by hbm2java
 */
public class TbUserLog implements java.io.Serializable {

	private Long id;
	private Long userId;
	private Date optTime;
	private Boolean optType;
	private String serverType;
	private String clientIp;
	private String clientAgent;

	public TbUserLog() {
	}

	public TbUserLog(Long userId, Date optTime, Boolean optType, String serverType, String clientIp,
			String clientAgent) {
		this.userId = userId;
		this.optTime = optTime;
		this.optType = optType;
		this.serverType = serverType;
		this.clientIp = clientIp;
		this.clientAgent = clientAgent;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Date getOptTime() {
		return this.optTime;
	}

	public void setOptTime(Date optTime) {
		this.optTime = optTime;
	}

	public Boolean getOptType() {
		return this.optType;
	}

	public void setOptType(Boolean optType) {
		this.optType = optType;
	}

	public String getServerType() {
		return this.serverType;
	}

	public void setServerType(String serverType) {
		this.serverType = serverType;
	}

	public String getClientIp() {
		return this.clientIp;
	}

	public void setClientIp(String clientIp) {
		this.clientIp = clientIp;
	}

	public String getClientAgent() {
		return this.clientAgent;
	}

	public void setClientAgent(String clientAgent) {
		this.clientAgent = clientAgent;
	}

}
