package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbUserBlack generated by hbm2java
 */
public class TbUserBlack implements java.io.Serializable {

	private Long id;
	private Long userId;
	private Long blackUserId;
	private String ctime;

	public TbUserBlack() {
	}

	public TbUserBlack(Long userId, Long blackUserId, String ctime) {
		this.userId = userId;
		this.blackUserId = blackUserId;
		this.ctime = ctime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getBlackUserId() {
		return this.blackUserId;
	}

	public void setBlackUserId(Long blackUserId) {
		this.blackUserId = blackUserId;
	}

	public String getCtime() {
		return this.ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

}
