package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbUserJob generated by hbm2java
 */
public class TbUserJob implements java.io.Serializable {

	private Long id;
	private String beginTime;
	private String department;
	private String description;
	private String endTime;
	private String inc;
	private String industry;
	private String position;
	private long userId;
	private String industryIds;

	public TbUserJob() {
	}

	public TbUserJob(long userId) {
		this.userId = userId;
	}

	public TbUserJob(String beginTime, String department, String description, String endTime, String inc,
			String industry, String position, long userId, String industryIds) {
		this.beginTime = beginTime;
		this.department = department;
		this.description = description;
		this.endTime = endTime;
		this.inc = inc;
		this.industry = industry;
		this.position = position;
		this.userId = userId;
		this.industryIds = industryIds;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(String beginTime) {
		this.beginTime = beginTime;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getInc() {
		return this.inc;
	}

	public void setInc(String inc) {
		this.inc = inc;
	}

	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getIndustryIds() {
		return this.industryIds;
	}

	public void setIndustryIds(String industryIds) {
		this.industryIds = industryIds;
	}

}
