package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbUserDynamic generated by hbm2java
 */
public class TbUserDynamic implements java.io.Serializable {

	private Long id;
	private String industryOptionId;
	private String industryOptionName;
	private String jsxqYn;
	private String rzxqOptionId;
	private String rzxqOptionName;
	private String rzxqYn;
	private String typeOptionId;
	private String typeOptionName;
	private String tzxqYn;
	private long userId;
	private String zjxqOptionId;
	private String zjxqOptionName;

	public TbUserDynamic() {
	}

	public TbUserDynamic(long userId) {
		this.userId = userId;
	}

	public TbUserDynamic(String industryOptionId, String industryOptionName, String jsxqYn, String rzxqOptionId,
			String rzxqOptionName, String rzxqYn, String typeOptionId, String typeOptionName, String tzxqYn,
			long userId, String zjxqOptionId, String zjxqOptionName) {
		this.industryOptionId = industryOptionId;
		this.industryOptionName = industryOptionName;
		this.jsxqYn = jsxqYn;
		this.rzxqOptionId = rzxqOptionId;
		this.rzxqOptionName = rzxqOptionName;
		this.rzxqYn = rzxqYn;
		this.typeOptionId = typeOptionId;
		this.typeOptionName = typeOptionName;
		this.tzxqYn = tzxqYn;
		this.userId = userId;
		this.zjxqOptionId = zjxqOptionId;
		this.zjxqOptionName = zjxqOptionName;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getIndustryOptionId() {
		return this.industryOptionId;
	}

	public void setIndustryOptionId(String industryOptionId) {
		this.industryOptionId = industryOptionId;
	}

	public String getIndustryOptionName() {
		return this.industryOptionName;
	}

	public void setIndustryOptionName(String industryOptionName) {
		this.industryOptionName = industryOptionName;
	}

	public String getJsxqYn() {
		return this.jsxqYn;
	}

	public void setJsxqYn(String jsxqYn) {
		this.jsxqYn = jsxqYn;
	}

	public String getRzxqOptionId() {
		return this.rzxqOptionId;
	}

	public void setRzxqOptionId(String rzxqOptionId) {
		this.rzxqOptionId = rzxqOptionId;
	}

	public String getRzxqOptionName() {
		return this.rzxqOptionName;
	}

	public void setRzxqOptionName(String rzxqOptionName) {
		this.rzxqOptionName = rzxqOptionName;
	}

	public String getRzxqYn() {
		return this.rzxqYn;
	}

	public void setRzxqYn(String rzxqYn) {
		this.rzxqYn = rzxqYn;
	}

	public String getTypeOptionId() {
		return this.typeOptionId;
	}

	public void setTypeOptionId(String typeOptionId) {
		this.typeOptionId = typeOptionId;
	}

	public String getTypeOptionName() {
		return this.typeOptionName;
	}

	public void setTypeOptionName(String typeOptionName) {
		this.typeOptionName = typeOptionName;
	}

	public String getTzxqYn() {
		return this.tzxqYn;
	}

	public void setTzxqYn(String tzxqYn) {
		this.tzxqYn = tzxqYn;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getZjxqOptionId() {
		return this.zjxqOptionId;
	}

	public void setZjxqOptionId(String zjxqOptionId) {
		this.zjxqOptionId = zjxqOptionId;
	}

	public String getZjxqOptionName() {
		return this.zjxqOptionName;
	}

	public void setZjxqOptionName(String zjxqOptionName) {
		this.zjxqOptionName = zjxqOptionName;
	}

}
