package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * TbUserConfig generated by hbm2java
 */
public class TbUserConfig implements java.io.Serializable {

	private Long id;
	private Long userId;
	private Integer nameVisible;
	private Integer sexVisible;
	private Integer ageVisible;
	private Integer birthdayVisible;
	private Integer faithVisible;
	private Integer jobVisible;
	private Integer emailVisible;
	private Integer mobileVisible;
	private Integer msnVisible;
	private Integer qqVisible;
	private Integer provinceVisible;
	private Integer cityVisible;
	private Integer industryVisible;
	private Integer companyNameVisible;
	private Integer companyAddressVisible;
	private Integer companyPostcodeVisible;
	private Integer companyJobVisible;
	private Integer companyPhoneVisible;
	private Integer companyFaxVisible;
	private Integer addressVisible;
	private Integer phoneVisible;
	private Integer postcodeVisible;
	private Integer xqVisible;
	private Integer specialVisible;
	private Integer zyVisible;
	private Integer educationVisible;
	private Date ctime;
	private Date utime;
	private Integer baseVisible;
	private Integer contactVisible;
	private Integer personalInfoVisible;
	private Integer zjxqVisible;
	private Integer socialaActVisible;
	private Integer mettingVisible;
	private Integer homePageVisible;
	private Integer evaluateVisible;
	private Integer dynamicVisible;
	private Integer dndVisible;
	private String dndStartTime;
	private String dndEndTime;
	private Integer autosave;

	public TbUserConfig() {
	}

	public TbUserConfig(Long userId, Integer nameVisible, Integer sexVisible, Integer ageVisible,
			Integer birthdayVisible, Integer faithVisible, Integer jobVisible, Integer emailVisible,
			Integer mobileVisible, Integer msnVisible, Integer qqVisible, Integer provinceVisible, Integer cityVisible,
			Integer industryVisible, Integer companyNameVisible, Integer companyAddressVisible,
			Integer companyPostcodeVisible, Integer companyJobVisible, Integer companyPhoneVisible,
			Integer companyFaxVisible, Integer addressVisible, Integer phoneVisible, Integer postcodeVisible,
			Integer xqVisible, Integer specialVisible, Integer zyVisible, Integer educationVisible, Date ctime,
			Date utime, Integer baseVisible, Integer contactVisible, Integer personalInfoVisible, Integer zjxqVisible,
			Integer socialaActVisible, Integer mettingVisible, Integer homePageVisible, Integer evaluateVisible,
			Integer dynamicVisible, Integer dndVisible, String dndStartTime, String dndEndTime, Integer autosave) {
		this.userId = userId;
		this.nameVisible = nameVisible;
		this.sexVisible = sexVisible;
		this.ageVisible = ageVisible;
		this.birthdayVisible = birthdayVisible;
		this.faithVisible = faithVisible;
		this.jobVisible = jobVisible;
		this.emailVisible = emailVisible;
		this.mobileVisible = mobileVisible;
		this.msnVisible = msnVisible;
		this.qqVisible = qqVisible;
		this.provinceVisible = provinceVisible;
		this.cityVisible = cityVisible;
		this.industryVisible = industryVisible;
		this.companyNameVisible = companyNameVisible;
		this.companyAddressVisible = companyAddressVisible;
		this.companyPostcodeVisible = companyPostcodeVisible;
		this.companyJobVisible = companyJobVisible;
		this.companyPhoneVisible = companyPhoneVisible;
		this.companyFaxVisible = companyFaxVisible;
		this.addressVisible = addressVisible;
		this.phoneVisible = phoneVisible;
		this.postcodeVisible = postcodeVisible;
		this.xqVisible = xqVisible;
		this.specialVisible = specialVisible;
		this.zyVisible = zyVisible;
		this.educationVisible = educationVisible;
		this.ctime = ctime;
		this.utime = utime;
		this.baseVisible = baseVisible;
		this.contactVisible = contactVisible;
		this.personalInfoVisible = personalInfoVisible;
		this.zjxqVisible = zjxqVisible;
		this.socialaActVisible = socialaActVisible;
		this.mettingVisible = mettingVisible;
		this.homePageVisible = homePageVisible;
		this.evaluateVisible = evaluateVisible;
		this.dynamicVisible = dynamicVisible;
		this.dndVisible = dndVisible;
		this.dndStartTime = dndStartTime;
		this.dndEndTime = dndEndTime;
		this.autosave = autosave;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Integer getNameVisible() {
		return this.nameVisible;
	}

	public void setNameVisible(Integer nameVisible) {
		this.nameVisible = nameVisible;
	}

	public Integer getSexVisible() {
		return this.sexVisible;
	}

	public void setSexVisible(Integer sexVisible) {
		this.sexVisible = sexVisible;
	}

	public Integer getAgeVisible() {
		return this.ageVisible;
	}

	public void setAgeVisible(Integer ageVisible) {
		this.ageVisible = ageVisible;
	}

	public Integer getBirthdayVisible() {
		return this.birthdayVisible;
	}

	public void setBirthdayVisible(Integer birthdayVisible) {
		this.birthdayVisible = birthdayVisible;
	}

	public Integer getFaithVisible() {
		return this.faithVisible;
	}

	public void setFaithVisible(Integer faithVisible) {
		this.faithVisible = faithVisible;
	}

	public Integer getJobVisible() {
		return this.jobVisible;
	}

	public void setJobVisible(Integer jobVisible) {
		this.jobVisible = jobVisible;
	}

	public Integer getEmailVisible() {
		return this.emailVisible;
	}

	public void setEmailVisible(Integer emailVisible) {
		this.emailVisible = emailVisible;
	}

	public Integer getMobileVisible() {
		return this.mobileVisible;
	}

	public void setMobileVisible(Integer mobileVisible) {
		this.mobileVisible = mobileVisible;
	}

	public Integer getMsnVisible() {
		return this.msnVisible;
	}

	public void setMsnVisible(Integer msnVisible) {
		this.msnVisible = msnVisible;
	}

	public Integer getQqVisible() {
		return this.qqVisible;
	}

	public void setQqVisible(Integer qqVisible) {
		this.qqVisible = qqVisible;
	}

	public Integer getProvinceVisible() {
		return this.provinceVisible;
	}

	public void setProvinceVisible(Integer provinceVisible) {
		this.provinceVisible = provinceVisible;
	}

	public Integer getCityVisible() {
		return this.cityVisible;
	}

	public void setCityVisible(Integer cityVisible) {
		this.cityVisible = cityVisible;
	}

	public Integer getIndustryVisible() {
		return this.industryVisible;
	}

	public void setIndustryVisible(Integer industryVisible) {
		this.industryVisible = industryVisible;
	}

	public Integer getCompanyNameVisible() {
		return this.companyNameVisible;
	}

	public void setCompanyNameVisible(Integer companyNameVisible) {
		this.companyNameVisible = companyNameVisible;
	}

	public Integer getCompanyAddressVisible() {
		return this.companyAddressVisible;
	}

	public void setCompanyAddressVisible(Integer companyAddressVisible) {
		this.companyAddressVisible = companyAddressVisible;
	}

	public Integer getCompanyPostcodeVisible() {
		return this.companyPostcodeVisible;
	}

	public void setCompanyPostcodeVisible(Integer companyPostcodeVisible) {
		this.companyPostcodeVisible = companyPostcodeVisible;
	}

	public Integer getCompanyJobVisible() {
		return this.companyJobVisible;
	}

	public void setCompanyJobVisible(Integer companyJobVisible) {
		this.companyJobVisible = companyJobVisible;
	}

	public Integer getCompanyPhoneVisible() {
		return this.companyPhoneVisible;
	}

	public void setCompanyPhoneVisible(Integer companyPhoneVisible) {
		this.companyPhoneVisible = companyPhoneVisible;
	}

	public Integer getCompanyFaxVisible() {
		return this.companyFaxVisible;
	}

	public void setCompanyFaxVisible(Integer companyFaxVisible) {
		this.companyFaxVisible = companyFaxVisible;
	}

	public Integer getAddressVisible() {
		return this.addressVisible;
	}

	public void setAddressVisible(Integer addressVisible) {
		this.addressVisible = addressVisible;
	}

	public Integer getPhoneVisible() {
		return this.phoneVisible;
	}

	public void setPhoneVisible(Integer phoneVisible) {
		this.phoneVisible = phoneVisible;
	}

	public Integer getPostcodeVisible() {
		return this.postcodeVisible;
	}

	public void setPostcodeVisible(Integer postcodeVisible) {
		this.postcodeVisible = postcodeVisible;
	}

	public Integer getXqVisible() {
		return this.xqVisible;
	}

	public void setXqVisible(Integer xqVisible) {
		this.xqVisible = xqVisible;
	}

	public Integer getSpecialVisible() {
		return this.specialVisible;
	}

	public void setSpecialVisible(Integer specialVisible) {
		this.specialVisible = specialVisible;
	}

	public Integer getZyVisible() {
		return this.zyVisible;
	}

	public void setZyVisible(Integer zyVisible) {
		this.zyVisible = zyVisible;
	}

	public Integer getEducationVisible() {
		return this.educationVisible;
	}

	public void setEducationVisible(Integer educationVisible) {
		this.educationVisible = educationVisible;
	}

	public Date getCtime() {
		return this.ctime;
	}

	public void setCtime(Date ctime) {
		this.ctime = ctime;
	}

	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	public Integer getBaseVisible() {
		return this.baseVisible;
	}

	public void setBaseVisible(Integer baseVisible) {
		this.baseVisible = baseVisible;
	}

	public Integer getContactVisible() {
		return this.contactVisible;
	}

	public void setContactVisible(Integer contactVisible) {
		this.contactVisible = contactVisible;
	}

	public Integer getPersonalInfoVisible() {
		return this.personalInfoVisible;
	}

	public void setPersonalInfoVisible(Integer personalInfoVisible) {
		this.personalInfoVisible = personalInfoVisible;
	}

	public Integer getZjxqVisible() {
		return this.zjxqVisible;
	}

	public void setZjxqVisible(Integer zjxqVisible) {
		this.zjxqVisible = zjxqVisible;
	}

	public Integer getSocialaActVisible() {
		return this.socialaActVisible;
	}

	public void setSocialaActVisible(Integer socialaActVisible) {
		this.socialaActVisible = socialaActVisible;
	}

	public Integer getMettingVisible() {
		return this.mettingVisible;
	}

	public void setMettingVisible(Integer mettingVisible) {
		this.mettingVisible = mettingVisible;
	}

	public Integer getHomePageVisible() {
		return this.homePageVisible;
	}

	public void setHomePageVisible(Integer homePageVisible) {
		this.homePageVisible = homePageVisible;
	}

	public Integer getEvaluateVisible() {
		return this.evaluateVisible;
	}

	public void setEvaluateVisible(Integer evaluateVisible) {
		this.evaluateVisible = evaluateVisible;
	}

	public Integer getDynamicVisible() {
		return this.dynamicVisible;
	}

	public void setDynamicVisible(Integer dynamicVisible) {
		this.dynamicVisible = dynamicVisible;
	}

	public Integer getDndVisible() {
		return this.dndVisible;
	}

	public void setDndVisible(Integer dndVisible) {
		this.dndVisible = dndVisible;
	}

	public String getDndStartTime() {
		return this.dndStartTime;
	}

	public void setDndStartTime(String dndStartTime) {
		this.dndStartTime = dndStartTime;
	}

	public String getDndEndTime() {
		return this.dndEndTime;
	}

	public void setDndEndTime(String dndEndTime) {
		this.dndEndTime = dndEndTime;
	}

	public Integer getAutosave() {
		return this.autosave;
	}

	public void setAutosave(Integer autosave) {
		this.autosave = autosave;
	}

}
