package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbUserAll generated by hbm2java
 */
public class TbUserAll implements java.io.Serializable {

	private Long id;
	private long userId;
	private long allId;
	private String name;
	private String img;
	private String nameFirst;
	private String nameIndex;
	private String pinyin;
	private Integer type;
	private String comStr;

	public TbUserAll() {
	}

	public TbUserAll(long userId, long allId) {
		this.userId = userId;
		this.allId = allId;
	}

	public TbUserAll(long userId, long allId, String name, String img, String nameFirst, String nameIndex,
			String pinyin, Integer type, String comStr) {
		this.userId = userId;
		this.allId = allId;
		this.name = name;
		this.img = img;
		this.nameFirst = nameFirst;
		this.nameIndex = nameIndex;
		this.pinyin = pinyin;
		this.type = type;
		this.comStr = comStr;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getAllId() {
		return this.allId;
	}

	public void setAllId(long allId) {
		this.allId = allId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public String getNameFirst() {
		return this.nameFirst;
	}

	public void setNameFirst(String nameFirst) {
		this.nameFirst = nameFirst;
	}

	public String getNameIndex() {
		return this.nameIndex;
	}

	public void setNameIndex(String nameIndex) {
		this.nameIndex = nameIndex;
	}

	public String getPinyin() {
		return this.pinyin;
	}

	public void setPinyin(String pinyin) {
		this.pinyin = pinyin;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getComStr() {
		return this.comStr;
	}

	public void setComStr(String comStr) {
		this.comStr = comStr;
	}

}
