package gintong.phoenix.user;
// Generated 2016-7-7 15:43:20 by Hibernate Tools 5.1.0.Beta1

/**
 * TbUserEducation generated by hbm2java
 */
public class TbUserEducation implements java.io.Serializable {

	private Long id;
	private String abroad;
	private String beginTime;
	private int degree;
	private String description;
	private String endTime;
	private String major;
	private String school;
	private long userId;

	public TbUserEducation() {
	}

	public TbUserEducation(int degree, long userId) {
		this.degree = degree;
		this.userId = userId;
	}

	public TbUserEducation(String abroad, String beginTime, int degree, String description, String endTime,
			String major, String school, long userId) {
		this.abroad = abroad;
		this.beginTime = beginTime;
		this.degree = degree;
		this.description = description;
		this.endTime = endTime;
		this.major = major;
		this.school = school;
		this.userId = userId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getAbroad() {
		return this.abroad;
	}

	public void setAbroad(String abroad) {
		this.abroad = abroad;
	}

	public String getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(String beginTime) {
		this.beginTime = beginTime;
	}

	public int getDegree() {
		return this.degree;
	}

	public void setDegree(int degree) {
		this.degree = degree;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

}
