package gintong.phoenix.knowledge.db42.vo;
// Generated 2016-6-5 9:54:44 by Hibernate Tools 4.3.1.Final

/**
 * BigdataColumnTag generated by hbm2java
 */
public class BigdataColumnTag implements java.io.Serializable {

	private Long id;
	private String columnname;
	private String cont;

	public BigdataColumnTag() {
	}

	public BigdataColumnTag(String columnname, String cont) {
		this.columnname = columnname;
		this.cont = cont;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getColumnname() {
		return this.columnname;
	}

	public void setColumnname(String columnname) {
		this.columnname = columnname;
	}

	public String getCont() {
		return this.cont;
	}

	public void setCont(String cont) {
		this.cont = cont;
	}

}
